# Q1. What are the benefits of the built-in array package, if any?

In theses array packag we have benifit of we can use many more its methods nd parameters and also nested modules.It will 
 take lese space as compared to other datatype in the python module.

# Q2. What are some of the array package's limitations?

we can not ncrease the size of array if once we declared.As it is an mutable entity.
 array occupies an amount of memory that is proportional to its size, independently of the number of elements that are actually of interest

# Q3. Describe the main differences between the array and numpy packages.

In numpy array it's not possible to upcast or downcast the strings so t will give value error.
 But in array it's possible to store ant kind of data type here.
 2)Inatialization is optional for the array but it is not possible in case of numpy array

# Q4. Explain the distinctions between the empty, ones, and zeros functions.

In [3]:
import numpy as np

In [9]:
np.ones((4))

array([1., 1., 1., 1.])

In [3]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.array()
# ==>Empty is not possiblme in case of the array in ones it will give us one in the particular shape as we want.

# Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?

In [14]:
s=np.fromfunction(lambda i,j:j*i,(4,4),dtype=int)
s

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [12]:
callable(s)

False

# Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?


In [18]:
np.array((2,3,4))+3
# Yes it is possible.

array([5, 6, 7])

# Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

In [20]:
s=10
s+=np.array((1,23))

In [21]:
s

array([11, 33])

# Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?

In [4]:
np.array(('a','r','j','u','n'))

array(['a', 'r', 'j', 'u', 'n'], dtype='<U1')

# Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?


In [28]:
np.array((1,2,34))*np.array((0,0,0))

array([0, 0, 0])

# Q10. What is the best way to use a Boolean array to mask another array?

In [32]:
all(np.array((True,True)))

True

In [5]:
all(np.array((True,True,False,False)))

False

# Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.


In [68]:
a=np.arange(1,101)

In [38]:
np.std(a)

28.86607004772212

In [39]:
from scipy import stats

In [40]:
stats.tstd(a)

29.011491975882016

In [78]:
import pandas as pd
pd.Series(a).std()   

29.011491975882016

# 12. What is the dimensionality of a Boolean mask-generated array?

it has only sigle true false result that is it has (1,1) shape.